package exceptions;

public class Sample {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
try {
	throw new UserDefined();
}

catch(UserDefined e) {
	
}
System.out.println("in my sample");
	}

}
 